// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFfGq5_dWMkZjpjX694FH-Lv5-Jfj7z0',
    appId: '1:772321345756:web:02768adb916449fba07419',
    messagingSenderId: '772321345756',
    projectId: 'emergency-assistant-c8ff4',
    authDomain: 'emergency-assistant-c8ff4.firebaseapp.com',
    storageBucket: 'emergency-assistant-c8ff4.firebasestorage.app',
    measurementId: 'G-CR1655WJ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyc-YYnl98CGkE0YN6wOGIpWPsxjYn2Ao',
    appId: '1:772321345756:android:bc927d61fa116055a07419',
    messagingSenderId: '772321345756',
    projectId: 'emergency-assistant-c8ff4',
    storageBucket: 'emergency-assistant-c8ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OZ9FP0GV8SXpNkdaq3efanaojIgvNvM',
    appId: '1:772321345756:ios:95c55e50092f778ea07419',
    messagingSenderId: '772321345756',
    projectId: 'emergency-assistant-c8ff4',
    storageBucket: 'emergency-assistant-c8ff4.firebasestorage.app',
    iosBundleId: 'com.example.emergencyAssistant',
  );
}
